# This is a config for automatically deployed GitHub Pages,
# it contains basic options for theme / layout / plugins, 
# see https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll
#     https://jekyllrb.com/docs/configuration/
#
theme: jekyll-theme-hacker
title: UTL
description: Collection of self-contained header-only libraries for C++17 
