# __________________________________ CONTENTS ___________________________________
#
#    This is a workflow file for GitHub Actions that runs a matrix of tests
#    in a MacOS environment. The actions is triggered automatically on every
#    push or pull request. Run results are then archived as GitHub artifacts.
#
#    By default, MacOS links to 'libc++' stdlib.
# _______________________________________________________________________________

name: "Run tests: MacOS"

run-name: "Build & runs tests on MacOS"

on: [ push, pull_request ]

jobs:
  clang-matrix:
    strategy:
      matrix:
        os: [ macos-latest ]
        cxx: [ clang++-14, clang++-20 ]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
          
      - name: "Configure CMake"
        run: cmake --preset clang
        
      - name: "Build project"
        run: cmake --build --preset clang
        
      - name: "Run tests"
        run: ctest --preset clang
        
      - name: "Upload test artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: "artifact-${{matrix.os}}-${{matrix.cxx}}"
          path: |
            "build/Testing/"
            "build/CMakeCache.txt"
            "build/compile_commands.json"
            "build/DartConfiguration.tcl"
